config/routes.rb
Rails.application.routes.draw do
  
  get 'partner/login' => 'partner_sessions#new', as: 'partner_login'
  post 'partner/login' => 'partner_sessions#create'
  delete 'partner/signout' => 'partner_sessions#destroy'
  get 'partner/signup' => 'partners#new'
  post 'partner/signup' => 'partners#create'
  
  resources :partners, except: [:new]

  get 'partner/working' => 'partners#showWorking', as: 'partner_working'
  get 'user/booking' => 'users#showBooking', as: 'user_booking'

  root "homes#index"

  namespace :admin do
    # get 'sessions/new'
    # get 'sessions/create'
    # get 'sessions/destroy'
    resources :sessions, only: [:new, :create, :destroy]
    # get 'signup', to: 'users#new', as: 'signup'
    get 'login', to: 'sessions#new', as: 'login'
    get 'logout', to: 'sessions#destroy', as: 'logout'
    get '', to: 'admins#dashboard', as: 'dashboard'
    get 'dashboard', to: 'admins#dashboard'
    get 'users_list', to: 'admins#show_users', as: 'users_list'
    get 'resetpass', to: 'admins#resetpass', as: 'resetpass'
    post 'reset', to: 'admins#send_reset_mail', as: 'send_reset_mail'
    get 'newpassword' => 'reset_password#edit', as: 'new_password'
    post 'user_destroy' => 'admins#destroy_user', as: 'user_destroy'
    get 'partners_list', to: 'admins#show_partners', as: 'partners_list'
    post 'partner_destroy' => 'admins#destroy_partner', as: 'partner_destroy'
    post 'salary_edit' => 'admins#edit_salary', as: 'salary_edit'
  end

  get 'signin' => 'sessions#new'
  post 'signin' => 'sessions#create'
  delete 'signout' => 'sessions#destroy'
  get 'signup' => 'users#new'
  post 'signup' => 'users#create'

  get 'get_district' => 'homes#get_district'
  get 'partner_detail/:id' => 'homes#partner_detail'
  get 'staff_search' => 'partners#search', as: 'staff_search'
  post 'booking' => 'books#handleBook'

  post 'deleteBooking' => 'books#deleteBooking'
  post 'acceptBooking' => 'books#acceptBooking'
  
  resources :users, except: [:new]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :partner_password_resets, only: [:new, :create, :edit, :update]
  resources :partner_change_password

  get '/partner_detail/:id', to: 'homes#partner_detail', as: 'partner_detail'
  post 'createComment' => 'users#createComment', as: 'create_comment'
  post 'deleteComment' => 'homes#delete_comment'
  
end

app/controllers/partner_sessions_controller.rb
class PartnerSessionsController < ApplicationController
  include PartnerSessionsHelper
  def new
    redirect_to '/' if partner_logged_in?
  end

  def create
    user = Partner.find_by email: params[:session][:email].downcase
    if user&.authenticate(params[:session][:password])
      if user.activated?
        partner_log_in user
        params[:session][:remember_me] == "1" ? remember(user) : forget(user)
        redirect_back_or user
      else
        flash[:error] = "Please active your account first!"
        redirect_to root_path
      end
    else
      flash.now[:error] = "Login error!"
      render :new
    end
  end

  def destroy
    partner_log_out if partner_logged_in?
    flash[:success] = "You are logged out"
    redirect_to root_path
  end
end

app/helpers/partner_sessions_helper.rb
module PartnerSessionsHelper
    def partner_log_in user
      session[:partner_id] = user.id
    end
  
    def partner_logged_in?
      current_partner.present?
    end
  
    def partner_log_out
      forget current_partner
      session.delete :partner_id
      @current_user = nil
    end
  
    def partner_remember user
      user.remember
      cookies.permanent.signed[:partner_id] = user.id
      cookies.permanent[:partner_remember_token] = user.remember_token
    end
  
    def partner_forget user
      user.forget
      cookies.delete :partner_id
      cookies.delete :partner_remember_token
    end
  
    def redirect_back_or default
      redirect_to(session[:forwarding_url] || default)
      session.delete :forwarding_url
    end
  
    def store_location
      session[:forwarding_url] = request.original_url if request.get?
    end
  
    def current_partner
      if partner_id = session[:partner_id]
        @current_user ||= Partner.find_by id: partner_id
      elsif partner_id = cookies.signed[:partner_id]
        user = Partner.find_by id: partner_id
        if user&.authenticated?(:partner_remember, cookies[:partner_remember_token])
          partner_log_in user
          @current_user = user
        end
      end
    end
  end
  

app/views/partner_sessions/create.html.erb
<h1>PartnerSessions#create</h1>
<p>Find me in app/views/partner_sessions/create.html.erb</p>

app/views/partner_sessions/destroy.html.erb
<h1>PartnerSessions#destroy</h1>
<p>Find me in app/views/partner_sessions/destroy.html.erb</p>

app/views/partner_sessions/new.html.erb
<% content_for :for_content do %>
  <!-- ##### Breadcrumb Area Start ##### -->
  <div class="vizew-breadcrumb">
      <div class="container">
          <div class="row">
              <div class="col-12">
                  <nav aria-label="breadcrumb">
                      <ol class="breadcrumb">
                          <li class="breadcrumb-item"><a href="<%= root_path %>"><i class="fa fa-home" aria-hidden="true"></i> Home</a></li>
                          <li class="breadcrumb-item active" aria-current="page">Signin</li>
                      </ol>
                  </nav>
              </div>
          </div>
      </div>
  </div>
  <!-- ##### Breadcrumb Area End ##### -->

  <!-- ##### Login Area Start ##### -->
  <div class="vizew-login-area section-padding-80">
      <div class="container">
          <div class="row justify-content-center">
              <div class="col-12 col-md-6">
                  <div class="login-content">
                      <!-- Section Title -->
                      <div class="section-heading">
                          <h4>Login as our Partner, and have funny job!</h4>
                          <div class="line"></div>
                      </div>

                      <%= form_for :session, url: partner_login_path do |f| %>
                        <div class="form-group">
                          <%= f.email_field :email, placeholder: "Enter your email", class: "form-control" %>
                        </div>
                        <div class="form-group">
                          <%= f.password_field :password, placeholder: "Enter your password", class: "form-control" %>
                        </div>
                        <div class="form-group">
                            <div class="custom-control custom-checkbox mr-sm-2">
                                <!-- <input type="checkbox" class="custom-control-input" id="customControlAutosizing"> -->
                                <%= f.check_box :remember_me, class: "custom-control-input", id: "customControlAutosizing" %>
                                <label class="custom-control-label" for="customControlAutosizing">Remember me</label>
                                <%= link_to "Forgot Password", new_partner_password_reset_path, class: "float-right", style: "color: orange; font-size: 18px; font-weight: bold" %>
                            </div>
                        </div>
                        <%= f.submit "Login", class: "btn vizew-btn w-100 mt-30" %>

                        <p style="text-align:center">------- or -------</p>
                        <%= link_to "Login as User", signin_path, class: "btn vizew-btn w-100", style: "background-color:#4437db" %>
                        <div class="text-right">New to Website?
                          <%= link_to "Register", partner_signup_path %>
                        </div>
                      <% end %>
                  </div>
              </div>
          </div>
      </div>
  </div>
  <!-- ##### Login Area End ##### -->
<% end %>