config/routes.rb
Rails.application.routes.draw do
  
  get 'partner/login' => 'partner_sessions#new', as: 'partner_login'
  post 'partner/login' => 'partner_sessions#create'
  delete 'partner/signout' => 'partner_sessions#destroy'
  get 'partner/signup' => 'partners#new'
  post 'partner/signup' => 'partners#create'
  
  resources :partners, except: [:new]

  get 'partner/working' => 'partners#showWorking', as: 'partner_working'
  get 'user/booking' => 'users#showBooking', as: 'user_booking'

  root "homes#index"

  namespace :admin do
    # get 'sessions/new'
    # get 'sessions/create'
    # get 'sessions/destroy'
    resources :sessions, only: [:new, :create, :destroy]
    # get 'signup', to: 'users#new', as: 'signup'
    get 'login', to: 'sessions#new', as: 'login'
    get 'logout', to: 'sessions#destroy', as: 'logout'
    get '', to: 'admins#dashboard', as: 'dashboard'
    get 'dashboard', to: 'admins#dashboard'
    get 'users_list', to: 'admins#show_users', as: 'users_list'
    get 'resetpass', to: 'admins#resetpass', as: 'resetpass'
    post 'reset', to: 'admins#send_reset_mail', as: 'send_reset_mail'
    get 'newpassword' => 'reset_password#edit', as: 'new_password'
    post 'user_destroy' => 'admins#destroy_user', as: 'user_destroy'
    get 'partners_list', to: 'admins#show_partners', as: 'partners_list'
    post 'partner_destroy' => 'admins#destroy_partner', as: 'partner_destroy'
    post 'salary_edit' => 'admins#edit_salary', as: 'salary_edit'
  end

  get 'signin' => 'sessions#new'
  post 'signin' => 'sessions#create'
  delete 'signout' => 'sessions#destroy'
  get 'signup' => 'users#new'
  post 'signup' => 'users#create'

  get 'get_district' => 'homes#get_district'
  get 'partner_detail/:id' => 'homes#partner_detail'
  get 'staff_search' => 'partners#search', as: 'staff_search'
  post 'booking' => 'books#handleBook'

  post 'deleteBooking' => 'books#deleteBooking'
  post 'acceptBooking' => 'books#acceptBooking'
  
  resources :users, except: [:new]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :partner_password_resets, only: [:new, :create, :edit, :update]
  resources :partner_change_password

  get '/partner_detail/:id', to: 'homes#partner_detail', as: 'partner_detail'
  post 'createComment' => 'users#createComment', as: 'create_comment'
  post 'deleteComment' => 'homes#delete_comment'
  
end

app/views/admin/admins/_form.html.erb
<%= form_with(model: admin_admin, local: true) do |form| %>
  <% if admin_admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_admin.errors.count, "error") %> prohibited this admin_admin from being saved:</h2>

      <ul>
      <% admin_admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/admins/dashboard.html.erb
<% content_for :for_head do %>
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <%# <script src="https://www.chartjs.org/dist/2.9.3/Chart.min.js"></script> %>
  <script src="https://www.chartjs.org/samples/latest/utils.js"></script>
<% end %>
<section class="content">
      
      <div class="container-fluid">
        <h1 class="m-0 text-dark">Dashboard</h1>
        <!-- Small boxes (Stat box) -->
        <div class="row">
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-info">
              <div class="inner">
                <h3><%= @users_count%></h3>

                <p>Users</p>
              </div>
              <div class="icon">
                <i class="ion ion-person"></i>
              </div>
              <a href="<%= admin_users_list_path %>" class="small-box-footer">More info <i class="fas ion-forward"></i></a>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-success">
              <div class="inner">
                <h3><%= @partners_count %><sup style="font-size: 20px"></h3>

                <p>Partners</p>
              </div>
              <div class="icon">
                <i class="ion ion-android-walk"></i>
              </div>
              <a href="<%= admin_partners_list_path%>" class="small-box-footer">More info <i class="fas ion-forward"></i></a>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-warning">
              <div class="inner">
                <h3><%= @booking_count%></h3>

                <p>Booking</p>
              </div>
              <div class="icon">
                <i class="ion ion-android-hand"></i>
              </div>
              <a href="#" class="small-box-footer">More info <i class="fas ion-forward"></i></a>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-danger">
              <div class="inner">
                <h3><%= number_to_currency(@money*1000, unit: "", locale: :vi, precision: 0, format: "%n %u") %></h3>

                <p>Total money</p>
              </div>
              <div class="icon">
                ₫
              </div>
              <a href="#chart-label" class="small-box-footer">More info <i class="fas ion-forward"></i></a>
            </div>
          </div>
          <!-- ./col -->
        </div>
        <!-- /.row -->
        <!-- Main row -->
        <div class="row">
          <!-- Left col -->
          <section class="col-lg-7 connectedSortable ui-sortable">
            <div class="card">
              <div class="card-header ui-sortable-handle" style="cursor: move;">
                <h3 class="card-title">
                  <i id="chart-label" class="fas fa-chart-pie mr-1"></i>
                  Money
                </h3>
                <%# <div class="card-tools">
                  <ul class="nav nav-pills ml-auto">
                    <li class="nav-item">
                      <a class="nav-link active" href="#revenue-chart" data-toggle="tab">Area</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#sales-chart" data-toggle="tab">Donut</a>
                    </li>
                  </ul>
                </div> %>
              </div><!-- /.card-header -->
              <div class="card-body">
                <div class="tab-content p-0">
                  <div class="wrapper col-2"><canvas id="chart-2" style="height: 250px;"></canvas></div>
                </div>
              </div><!-- /.card-body -->
            </div>                     
            <!-- /.card -->
          </section>
          <!-- /.Left col -->
          <!-- right col (We are only adding the ID to make the widgets sortable)-->
          <section class="col-lg-5 connectedSortable ui-sortable">
            <div class="card bg-gradient-success">
              <div class="card-header border-0 ui-sortable-handle" style="cursor: move;">

                <h3 class="card-title">
                  <i class="ion ion-calendar"></i>
                  Calendar
                </h3>
                <!-- /. tools -->
              </div>
              <!-- /.card-header -->
              <div class="card-body pt-0">
                <!--The calendar -->
                <div id="calendar" style="width: 100%">
                  <div class="bootstrap-datetimepicker-widget usetwentyfour">
                    <ul class="list-unstyled"><li class="show"><div class="datepicker"><div class="datepicker-days" style="">
                    <table class="table table-sm">
                    <thead><tr><th class="prev" data-action="previous"></th>
                    <th class="picker-switch" data-action="pickerSwitch" colspan="5" title="Select Month">December 2019</th><th class="next" data-action="next"></th></tr><tr><th class="dow">Su</th><th class="dow">Mo</th><th class="dow">Tu</th><th class="dow">We</th><th class="dow">Th</th><th class="dow">Fr</th><th class="dow">Sa</th></tr></thead>
                    <tbody id="days-in-month">
                      <%# <tr><td data-action="selectDay" data-day="12/01/2019" class="day weekend">1</td></tr> %>
                    </tbody>
                    </table>
                  </div>
                </div>
              </div>
              <!-- /.card-body -->
            </div>
          </section>
          <!-- right col -->
        </div>
        <!-- /.row (main row) -->
      </div><!-- /.container-fluid -->
    </section>
<% content_for :for_js do%>
<script>
function daysInMonth (month, year) {
    return new Date(year, month, 0).getDate();
}
var days = daysInMonth(12, 2019);
for (var i = 0; i <= days / 7; i++){
    var tr = document.createElement('tr');
    for (var j = 0; j < 7; j++) {
        var day = 1 + (i * 7 + j) % days;
        var today = new Date().getDate() == day ? "active" : '';
        var newday = 1 + (i * 7 + j) > days ? "new" : '';
        tr.innerHTML += '<td data-action="selectDay" class="day ' + newday + ' ' + today + '">' + day + '</td>';
    }
    $('#days-in-month').append(tr)
}

var month_data = JSON.parse(new DOMParser().parseFromString("<%=@money_month%>", 'text/html').body.textContent);

var presets = window.chartColors;
var utils = Samples.utils;
var inputs = {
    min: -100,
    max: 100,
    count: 8,
    decimals: 2,
    continuity: 1
};

		var options = {
			maintainAspectRatio: false,
			spanGaps: false,
			elements: {
				line: {
					tension: 0.000001
				}
			},
			plugins: {
				filler: {
					propagate: false
				}
			},
			scales: {
				xAxes: [{
					ticks: {
						autoSkip: false,
						maxRotation: 0
					}
				}]
			}
		};

			// reset the random seed to generate the same data for all charts
			utils.srand(8);

			var money_chart = new Chart('chart-2', {
				type: 'line',
				data: {
					labels: Object.keys(month_data).map(x=> x.split('-')[2]),
					datasets: [{
						backgroundColor: utils.transparentize(presets.red),
						borderColor: presets.red,
						data: Object.values(month_data),
						label: 'Thousand VND',
						fill: 'start'
					}]
				},
				options: Chart.helpers.merge(options, {
					title: {
						text: (new Date().getFullYear())+'/' +(1+new Date().getMonth()),
						display: true
					}
				})
			});


      money_chart.options.elements.line.tension = 0.4;
      money_chart.update();

</script>
<% end %>

app/views/admin/admins/edit.html.erb
<h1>Editing Admin Admin</h1>

<%= render 'form', admin_admin: session[:admin_id] %>

<%= link_to 'Show', @admin_admin %> |
<%= link_to 'Back', admin_admins_path %>

app/views/admin/admins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Admins</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_admins.each do |admin_admin| %>
      <tr>
        <td><%= admin_admin.email %></td>
        <td><%= link_to 'Show', admin_admin %></td>
        <td><%= link_to 'Edit', edit_admin_admin_path(admin_admin) %></td>
        <td><%= link_to 'Destroy', admin_admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Admin', new_admin_admin_path %>

app/views/admin/admins/new.html.erb
<h1>New Admin Admin</h1>

<%= render 'form', admin_admin: @admin_admin %>

<%= link_to 'Back', admin_admins_path %>

app/views/admin/admins/resetpass.html.erb
<% content_for :for_head do %>
  <%= stylesheet_link_tag    'admin/login', media: 'all', 'data-turbolinks-track': 'reload' %>
<% end %>
<meta name="viewport" content="initial-scale=1.0, width=device-width" />
<title>Reset password</title>
<link rel="stylesheet" type="text/css" href="https://js.api.here.com/v3/3.1/mapsjs-ui.css" />
<script type="text/javascript" src="https://js.api.here.com/v3/3.1/mapsjs-core.js"></script>
<script type="text/javascript" src="https://js.api.here.com/v3/3.1/mapsjs-service.js"></script>
<script type="text/javascript" src="https://js.api.here.com/v3/3.1/mapsjs-ui.js"></script>
<script type="text/javascript" src="https://js.api.here.com/v3/3.1/mapsjs-mapevents.js"></script>
<link rel="stylesheet" type="text/css" 
href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css"/>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>



<% content_for :for_content do %>
<div class="wrapper fadeInDown">
<div id="formContent">
  <!-- Tabs Titles -->

  <!-- Icon -->
  <div class="fadeIn first">
    <img src="https://image.flaticon.com/icons/svg/78/78948.svg" id="icon" style="width: 50px; margin: 15px;" alt="User Icon" />
    <span>Reset admin's password</span>
    <p style="color:red" id="alert"><%= alert %></p>
  </div>

  <%= form_tag admin_send_reset_mail_path do |form| %>
    <input type="text" id="login"  class="fadeIn second" name="email" placeholder="Admin Account">
    <input type="submit" class="fadeIn fourth" value="Send mail">
  <% end %>
  

</div>
</div>
<% end %>

app/views/admin/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @admin_admin.email %>
</p>

<%= link_to 'Edit', edit_admin_admin_path(@admin_admin) %> |
<%= link_to 'Back', admin_admins_path %>

app/views/admin/admins/show_partners.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Salary (Thousand VND)</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @partners.each do |partner| %>
        
            <tr id="partner<%= partner.id %>">
                
                    
                    <td><%= partner.name %></td>
                    <td><%= partner.email%></td>
                    <td><%= partner.phone%></td>
                    <td>
                      <input id="partner_salary_<%= partner.id %>" style="border: 0; background-color: inherit" type="number" readonly value="<%= partner.cost %>">
                    </td>
                    <td>    
                        <button onClick="deletePartner(this)" data-partner-id="<%= partner.id %>" type="submit" class="btn btn-danger">
                            Delete
                        </button>
                      <button onClick="handleSalary(this)" data-partner-id="<%= partner.id %>" data-salary-btn-status="0" class="btn btn-success">
                        Edit Salary
                      </button>
                    </td>
                
            </tr>
        
    <% end %>
  </tbody>
</table>

<% content_for :for_js do %>
  <script>
    function deletePartner(del_btn) {
      var r =  confirm("Do you want to delete the partner?");
      if (r == true) {
        var uid = del_btn.getAttribute("data-partner-id");

        var token = $( 'meta[name="csrf-token"]' ).attr( 'content' );

        $.ajaxSetup( {
          beforeSend: function ( xhr ) {
            xhr.setRequestHeader( 'X-CSRF-Token', token );
          }
        });

        $.ajax({
                url: '/admin/partner_destroy',
                type: 'POST',
                data: {
                  partner_id: uid
                }
            }).done(function(result) {
               $("#partner"+uid).remove();
               toastr.success(result.data);
            });
      } else {
        return false;
      }
    }

    function handleSalary(salary_btn) {
        var status = salary_btn.getAttribute("data-salary-btn-status");
        var uid = salary_btn.getAttribute("data-partner-id");
        if(status == "1") {
            var token = $( 'meta[name="csrf-token"]' ).attr( 'content' );

            $.ajaxSetup( {
                beforeSend: function ( xhr ) {
                    xhr.setRequestHeader( 'X-CSRF-Token', token );
                }
            });

            $.ajax({
                url: '/admin/salary_edit',
                type: 'POST',
                data: {
                    partner_id: uid,
                    salary: $("#partner_salary_"+uid).val()
                }
            }).done(function(result) {
                toastr.success(result.data);
                salary_btn.setAttribute("data-salary-btn-status", 0);
                $("#partner_salary_"+uid).attr("readonly", true);
                $("#partner_salary_"+uid).css("background-color", "inherit");
                salary_btn.innerHTML = "Edit Salary";
                $(salary_btn).removeClass("btn-primary").addClass("btn-success");
            });
        }else {
            $("#partner_salary_"+uid).attr("readonly", false);
            $("#partner_salary_"+uid).css("background-color", "white");
            $("#partner_salary_"+uid).focus();
            $("#partner_salary_"+uid).select();
            salary_btn.innerHTML = "Save";
            $(salary_btn).removeClass("btn-success").addClass("btn-primary");
            salary_btn.setAttribute("data-salary-btn-status", 1);
        }
    }
  </script>
<% end %>

app/views/admin/admins/show_users.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
        
            <tr id="user<%= user.id %>">
                
                    
                    <td><%= user.name %></td>
                    <td><%= user.email%></td>
                    <td><%= user.phone%></td>
                    <td>    
                        <button onClick="deleteUser(this)" data-user-id="<%= user.id %>" type="submit" class="btn btn-danger">
                            Delete
                        </button></td>
                
            </tr>
        
    <% end %>
  </tbody>
</table>

<% content_for :for_js do %>
  <script>
    function deleteUser(del_btn) {
      var r =  confirm("Do you want to delete the user?");
      if (r == true) {
        var uid = del_btn.getAttribute("data-user-id");

        var token = $( 'meta[name="csrf-token"]' ).attr( 'content' );

        $.ajaxSetup( {
          beforeSend: function ( xhr ) {
            xhr.setRequestHeader( 'X-CSRF-Token', token );
          }
        });

        $.ajax({
                url: '/admin/user_destroy',
                type: 'POST',
                data: {
                    user_id: uid
                }
            }).done(function(result) {
               $("#user"+uid).remove();
               toastr.success(result.data);
            });
      } else {
        return false;
      }
    }
  </script>
<% end %>