config/routes.rb
Rails.application.routes.draw do
  
  get 'partner/login' => 'partner_sessions#new', as: 'partner_login'
  post 'partner/login' => 'partner_sessions#create'
  delete 'partner/signout' => 'partner_sessions#destroy'
  get 'partner/signup' => 'partners#new'
  post 'partner/signup' => 'partners#create'
  
  resources :partners, except: [:new]

  get 'partner/working' => 'partners#showWorking', as: 'partner_working'
  get 'user/booking' => 'users#showBooking', as: 'user_booking'

  root "homes#index"

  namespace :admin do
    # get 'sessions/new'
    # get 'sessions/create'
    # get 'sessions/destroy'
    resources :sessions, only: [:new, :create, :destroy]
    # get 'signup', to: 'users#new', as: 'signup'
    get 'login', to: 'sessions#new', as: 'login'
    get 'logout', to: 'sessions#destroy', as: 'logout'
    get '', to: 'admins#dashboard', as: 'dashboard'
    get 'dashboard', to: 'admins#dashboard'
    get 'users_list', to: 'admins#show_users', as: 'users_list'
    get 'resetpass', to: 'admins#resetpass', as: 'resetpass'
    post 'reset', to: 'admins#send_reset_mail', as: 'send_reset_mail'
    get 'newpassword' => 'reset_password#edit', as: 'new_password'
    post 'user_destroy' => 'admins#destroy_user', as: 'user_destroy'
    get 'partners_list', to: 'admins#show_partners', as: 'partners_list'
    post 'partner_destroy' => 'admins#destroy_partner', as: 'partner_destroy'
    post 'salary_edit' => 'admins#edit_salary', as: 'salary_edit'
  end

  get 'signin' => 'sessions#new'
  post 'signin' => 'sessions#create'
  delete 'signout' => 'sessions#destroy'
  get 'signup' => 'users#new'
  post 'signup' => 'users#create'

  get 'get_district' => 'homes#get_district'
  get 'partner_detail/:id' => 'homes#partner_detail'
  get 'staff_search' => 'partners#search', as: 'staff_search'
  post 'booking' => 'books#handleBook'

  post 'deleteBooking' => 'books#deleteBooking'
  post 'acceptBooking' => 'books#acceptBooking'
  
  resources :users, except: [:new]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :partner_password_resets, only: [:new, :create, :edit, :update]
  resources :partner_change_password

  get '/partner_detail/:id', to: 'homes#partner_detail', as: 'partner_detail'
  post 'createComment' => 'users#createComment', as: 'create_comment'
  post 'deleteComment' => 'homes#delete_comment'
  
end

app/views/layouts/_footer.html.erb
<!-- ##### Footer Area Start ##### -->
<footer class="footer-area">
    <div class="container">
        <div class="row">
            <!-- Footer Widget Area -->
            <div class="col-12 col-sm-6 col-xl-3">
                <div class="footer-widget mb-70">
                    <!-- Logo -->
                  <a href="/" class="foo-logo d-block mb-4"><h1>Cleany</h1></a>
                  <p>More Cleany</p>
                    <!-- Footer Newsletter Area -->
                    <div class="footer-nl-area">
                        <form action="#" method="post">
                            <input type="email" name="nl-email" class="form-control" id="nlEmail" placeholder="Your email">
                            <button type="submit"><i class="fa fa-paper-plane" aria-hidden="true"></i></button>
                        </form>
                    </div>
                </div>
            </div>

            <!-- Footer Widget Area -->
            <div class="col-12 col-sm-6 col-xl-3">
                <div class="footer-widget mb-70">

                </div>
            </div>

            <!-- Footer Widget Area -->
            <div class="col-12 col-sm-6 col-xl-3">
                <div class="footer-widget mb-70">
                </div>
            </div>

            <!-- Footer Widget Area -->
            <div class="col-12 col-sm-6 col-xl-3">
                <div class="footer-widget mb-70">
                    <h6 class="widget-title">Our Address</h6>
                    <!-- Contact Address -->
                    <div class="contact-address">
                      <p>101 Chinh Kinh, Ha Noi</p>
                      <p>Phone: +84xxxxxxxxx</p>
                      <p>Email: xxx@gmail.com</p>
                    </div>
                    <!-- Footer Social Area -->
                    <div class="footer-social-area">
                        <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
                        <a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a>
                        <a href="#" class="instagram"><i class="fa fa-instagram"></i></a>
                        <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
                        <a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Copywrite Area -->
    <div class="copywrite-area">
        <div class="container">
            <div class="row align-items-center">
                <!-- Copywrite Text -->
                <div class="col-12 col-sm-6">
                  <p class="copywrite-text">Copyright ミズギ　2019</p>
                </div>
                <div class="col-12 col-sm-6">
                    <nav class="footer-nav">
                        <ul>

                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- ##### Footer Area End ##### -->

app/views/layouts/_header.html.erb
<!-- Preloader -->
<!-- <div class="preloader d-flex align-items-center justify-content-center">
    <div class="lds-ellipsis">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
    </div>
</div> -->

<!-- ##### Header Area Start ##### -->
<header class="header-area" style="background:#db4437">
    <!-- Top Header Area -->
    <div class="top-header-area">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-12 col-md-6">

                </div>
                <div class="col-12 col-md-6">
                    <div class="top-meta-data d-flex align-items-center justify-content-end">
                        <!-- Top Social Info -->
                        <div class="top-social-info">
                            <a href="#"><i style="color:white" class="fa fa-facebook"></i></a>
                            <a href="#"><i style="color:white" class="fa fa-twitter"></i></a>
                            <a href="#"><i style="color:white" class="fa fa-youtube-play"></i></a>
                        </div>
                        <!-- Top Search Area -->
                        <!--
                        <div class="top-search-area">
                            <form action="index.html" method="post">
                                <input type="search" name="top-search" id="topSearch" placeholder="Search...">
                                <button type="submit" class="btn"><i class="fa fa-search" aria-hidden="true"></i></button>
                            </form>
                        </div>
                        -->
                        <!-- Login -->
                        <% if logged_in? %>
                            <div class="dropdown">
                                <a class="btn btn-secondary dropdown-toggle" style="color:white" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fa fa-user" aria-hidden="true"></i> <%= current_user.name %>
                                </a>
                              
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                  <a class="dropdown-item" href="<%= user_path(current_user.id) %>">User Profile</a>
                                  <a class="dropdown-item" href="#">Change Password </a>
                                  <%= link_to "Logout", signout_path, method: :delete, class: "dropdown-item" %>
                                  <!-- <a class="dropdown-item" href="<%= signout_path %>">Logout</a> -->
                                </div>
                            </div>
                        <% elsif partner_logged_in? %>
                            <div class="dropdown">
                                <a class="btn btn-secondary dropdown-toggle" style="color:white" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fa fa-reddit-alien" aria-hidden="true"></i> <%= current_partner.name %>
                                </a>
                              
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                  <a class="dropdown-item" href="<%= partner_path(current_partner.id) %>">User Profile</a>
                                  <a class="dropdown-item" href="<%= edit_partner_change_password_path(current_partner.id) %>">Change Password </a>
                                  <%= link_to "Logout", partner_signout_path, method: :delete, class: "dropdown-item" %>
                                  <!-- <a class="dropdown-item" href="<%= signout_path %>">Logout</a> -->
                                </div>
                            </div>    
                        <% else %>
                            <a href="<%= signin_path %>" class="login-btn">Login</a>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Navbar Area -->
    <div class="vizew-main-menu" id="sticker">
        <div class="classy-nav-container breakpoint-off">
            <div class="container">

                <!-- Menu -->
                <nav class="classy-navbar justify-content-between" id="vizewNav">

                    <!-- Nav brand -->
                    <a href="<%= root_path %>" class="nav-brand"><p style="color:white;font-size:-webkit-xxx-large">Cleany</p></a>

                    <!-- Navbar Toggler -->
                    <div class="classy-navbar-toggler">
                        <span class="navbarToggler"><span></span><span></span><span></span></span>
                    </div>

                    <div class="classy-menu">

                        <!-- Close Button -->
                        <div class="classycloseIcon">
                            <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                        </div>

                        <!-- Nav Start -->
                        <div class="classynav">
                            <ul>
                                <li class="active"><a href="<%= root_path %>">Home</a></li>
                                <% if current_partner %>
                                    <li><a href="<%= partner_working_path %>">Working Part</a></li>
                                <% end %>
                                <% if current_user %>
                                    <li><a href="<%= user_booking_path %>">Booking Part</a></li>
                                <% end %>
                                <%# <li><a href="#">Archives</a></li>
                                <li><a href="#">Features</a></li> %>
                                <li><a href="#">Contact</a></li>
                            </ul>
                        </div>
                        <!-- Nav End -->
                    </div>
                </nav>
            </div>
        </div>
    </div>
</header>
<!-- ##### Header Area End ##### -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield :title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %> -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'layout/css/style', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'toastr.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= yield(:for_head) %>
  </head>

  <body>
    <!-- <div class="container"> -->
      <% flash.each do |key, value| %>
        <script>toastr.<%= key %>("<%= value %>")</script>
      <% end %>
      <%= render "layouts/header" %>
      <%= yield(:for_content) %>
      <%= render "layouts/footer" %>
    <!-- </div> -->

    <%= yield(:for_js) %>
    <%= javascript_include_tag 'layout/js/jquery/jquery-2.2.4.min.js', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'layout/js/bootstrap/popper.min.js', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'layout/js/bootstrap/bootstrap.min.js', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'layout/js/plugins/plugins.js', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'layout/js/active.js', 'data-turbolinks-track': 'reload' %>
  </body>
</html>